Activity 8

In [3]:
import pandas as pd
import numpy as np

In [23]:
# Load the Dataset
df = pd.read_csv ("/content/brfss.csv")

In [24]:
# Read 1st 5 rows of the dataframe
data = df.head(5)
data

   Unnamed: 0   age     weight2     wtyrago   wtkg2   htm3  sex
0           0  39.0   88.636364   88.636364   88.64  180.0    1
1           1  64.0   75.000000   84.545455   75.00  155.0    2
2           2  87.0   61.818182   63.636364   61.82    NaN    2
3           3  51.0  100.000000  100.000000  100.00  183.0    1
4           4  35.0   63.636364   61.363636   63.64  170.0    2

In [25]:
# Drop the sex column from the dataframe
df = df.drop("sex", axis=1).head()
df

   Unnamed: 0   age     weight2     wtyrago   wtkg2   htm3
0           0  39.0   88.636364   88.636364   88.64  180.0
1           1  64.0   75.000000   84.545455   75.00  155.0
2           2  87.0   61.818182   63.636364   61.82    NaN
3           3  51.0  100.000000  100.000000  100.00  183.0
4           4  35.0   63.636364   61.363636   63.64  170.0

In [32]:
# Drop the rows of NAN value (every single NAN)
df_cleaned = df.dropna()
df_cleaned

   Unnamed: 0   age     weight2     wtyrago   wtkg2   htm3
0           0  39.0   88.636364   88.636364   88.64  180.0
1           1  64.0   75.000000   84.545455   75.00  155.0
3           3  51.0  100.000000  100.000000  100.00  183.0
4           4  35.0   63.636364   61.363636   63.64  170.0

In [28]:
df.describe()

       Unnamed: 0        age     weight2     wtyrago       wtkg2        htm3
count    5.000000   5.000000    5.000000    5.000000    5.000000    4.000000
mean     2.000000  55.200000   77.818182   79.636364   77.820000  172.000000
std      1.581139  21.076053   16.386978   16.655850   16.386348   12.622731
min      0.000000  35.000000   61.818182   61.363636   61.820000  155.000000
25%      1.000000  39.000000   63.636364   63.636364   63.640000  166.250000
50%      2.000000  51.000000   75.000000   84.545455   75.000000  175.000000
75%      3.000000  64.000000   88.636364   88.636364   88.640000  180.750000
max      4.000000  87.000000  100.000000  100.000000  100.000000  183.000000

In [36]:
df_describe = df["weight2"].describe(percentiles=[0.25, 0.50, 0.75])
df_describe

count      5.000000
mean      77.818182
std       16.386978
min       61.818182
25%       63.636364
50%       75.000000
75%       88.636364
max      100.000000
Name: weight2, dtype: float64

In [38]:
# find median and mode of age column

age_median = df["age"].median()
age_mode = df["age"].mode()
print ("Median of age_col is : ", age_median)
print ("Mode of age_col is : ", age_mode)

Median of age is :  51.0
Mode of age is :  0    35.0
1    39.0
2    51.0
3    64.0
4    87.0
Name: age, dtype: float64